### ISSUE TITLE
cabal install cabal-install failed

### ISSUE THREAD

**Issue by lichengqian** [sseefried/docker-build-ghc-android#10]
failed install cabal-install-1.22.4.0, i think it should work for another version ? anybody knows?

**Comment by sseefried** [comment]
Could you give me a little more information? The install worked when I last ran the script. Can you give me a full screen dump of what went wrong?

**Comment by sseefried** [comment]
One more question. Were you using Docker v1.6?

**Comment by lichengqian** [comment]
i use docker v1.6.2, it seems that error related to network-uri version dependency conflict.
and yes , it is during the step "RUN ./update-host-cabal.sh"
    after cabal update
            cabal install cabal-install -- run this line error

maybe later i will post the detailed screen dump info. thanks very much

发件人: Sean Seefried [mailto:notifications@github.com]
发送时间: 2015年6月3日 10:56
收件人: sseefried/docker-build-ghc-android
抄送: 李明
主题: Re: [docker-build-ghc-android] cabal install cabal-install failed (#10)


One more question. Were you using Docker v1.6?

—
Reply to this email directly or view it on GitHub<https://github.com/sseefried/docker-build-ghc-android/issues/10#issuecomment-108171159>.

________________________________

保密声明：
本邮件可能含有受到相关法律保护的特许保密性的、机密性的或者免予/禁止对外公开的内容。如果您不是预期的接收人，或者预期接收人的员工/代理人，现特此声明：严禁任何散布、分发、保留、存档或者复印本邮件以及/或者其中内容的行为。如果您因误发而收到这份邮件或者违反了以上所述，请立即通知发件人。

**Comment by sseefried** [comment]
I'm trying to work out how it could work differently on your machine. It's really interesting!

The version of network-uri that was installed on my machine was network-uri-2.6.0.3

What was your version?

**Comment by sseefried** [comment]
Also, I was using Docker v1.6.0. I wonder if being v1.6.2 could affect this. If so, I don't know how.

**Comment by sseefried** [comment]
Okay, I've changed the scriptlet to be more precise about the dependencies in 8871168e28831854d41e391519039e2e99213050

**Comment by lichengqian** [comment]
Step 20 : RUN ./update-host-cabal.sh
 ---> Running in 58fd9656e8d4
cabal: out of memory (requested 1048576 bytes)

cabal update always failed, and i googled it and find many other people have the same problem,

it seems a ghc bug, not related to the Dockerfile script. i am trying to resove this.

**Comment by lichengqian** [comment]
i change the virtual machine' memory from 512M to 2G, and it works!
