### ISSUE TITLE
Problem with cabal

### ISSUE THREAD

**Issue by gazay** [sseefried/docker-build-ghc-android#6]
Hello, I've built compiler and try to install https://github.com/neurocyte/foreign-jni after, but I have strange error: https://gist.github.com/gazay/d9a71cc79ea5d56f35cc

Do you have any clue what could go wrong and what I should try to solve this?

Great work on this image btw!

**Comment by gazay** [comment]
this worked for me http://stackoverflow.com/questions/25765893/how-do-i-install-dependencies-when-cross-compiling-haskell-code.

**Comment by sseefried** [comment]
Yep, that technique is one that works for many packages, but not all.
