### ISSUE TITLE
Separate the cross compilation work from the Android work.

### ISSUE THREAD

**Issue by seanparsons** [sseefried/docker-build-ghc-android#7]
This is probably the precursor to actually separating them and is more of a note for me to do it. I realised (after picking up my new Raspberry Pi) that it would be awesomely useful to have a docker file that does the cross compilation set up and another based on that which does the Android specific stuff on top of that.

**Comment by seanparsons** [comment]
On reflection I don't think this is really much of a thing.

**Comment by sseefried** [comment]
Sean, I'm still really keen to put that OpenGL app in. I've just been quite busy lately.

Could you tell me more about what you are using this docker image for? Something on a Raspberry Pi?

**Comment by seanparsons** [comment]
My thinking was that since this does all the work of getting an ARM cross compiler up and running for GHC in theory that means I could use it to build stuff for a Pi. I'm interested in this mostly because I want to build a little dashboard and would rather write it in Haskell. But previously when looking at building directly on the Pi it's virtually a non-starter because of the spec of it.
